/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbilityHeader: typeof import('./src/components/abilities/AbilityHeader.vue')['default']
    AbilitySelector: typeof import('./src/components/AbilitySelector.vue')['default']
    EffectCard: typeof import('./src/components/EffectCard.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    InkSaverMain: typeof import('./src/components/abilities/InkSaverMain.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PlotCard: typeof import('./src/components/PlotCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/StatsCard.vue')['default']
    StatsWithPlot: typeof import('./src/components/StatsWithPlot.vue')['default']
    SwimmSpeed: typeof import('./src/components/SwimmSpeed.vue')['default']
    SwimSpeed: typeof import('./src/components/abilities/SwimSpeed.vue')['default']
    WeaponList: typeof import('./src/components/WeaponList.vue')['default']
    WeaponSelector: typeof import('./src/components/WeaponSelector.vue')['default']
  }
}
