/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbilitySelector: typeof import('./src/components/AbilitySelector.vue')['default']
    BaseAbility: typeof import('./src/components/abilities/BaseAbility.vue')['default']
    EffectCard: typeof import('./src/components/EffectCard.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InkRecoveryUp: typeof import('./src/components/abilities/InkRecoveryUp.vue')['default']
    InkSaverMain: typeof import('./src/components/abilities/InkSaverMain.vue')['default']
    InkSaverSub: typeof import('./src/components/abilities/InkSaverSub.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PlotCard: typeof import('./src/components/PlotCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunSpeed: typeof import('./src/components/abilities/RunSpeed.vue')['default']
    SpecialChargeUp: typeof import('./src/components/abilities/SpecialChargeUp.vue')['default']
    SpecialIncreaseUp: typeof import('./src/components/abilities/SpecialIncreaseUp.vue')['default']
    SpecialSave: typeof import('./src/components/abilities/SpecialSave.vue')['default']
    SpecialSpecUp: typeof import('./src/components/abilities/SpecialSpecUp.vue')['default']
    StatsCard: typeof import('./src/components/StatsCard.vue')['default']
    StatsWithPlot: typeof import('./src/components/StatsWithPlot.vue')['default']
    SwimmSpeed: typeof import('./src/components/abilities/SwimmSpeed.vue')['default']
    SwimSpeed: typeof import('./src/components/abilities/SwimSpeed.vue')['default']
    WeaponSelector: typeof import('./src/components/WeaponSelector.vue')['default']
  }
}
